/**
 * ISO 3166-1 country list (commonly needed for KYC / onboarding).
 */

export interface CountryInfo {
  name: string;
  alpha2: string;
  alpha3: string;
  dialCode: string;
  /** ISO 4217 default currency code */
  currency: string;
}

export const COUNTRIES: CountryInfo[] = [
  { name: "United States", alpha2: "US", alpha3: "USA", dialCode: "+1", currency: "USD" },
  { name: "United Kingdom", alpha2: "GB", alpha3: "GBR", dialCode: "+44", currency: "GBP" },
  { name: "United Arab Emirates", alpha2: "AE", alpha3: "ARE", dialCode: "+971", currency: "AED" },
  { name: "Saudi Arabia", alpha2: "SA", alpha3: "SAU", dialCode: "+966", currency: "SAR" },
  { name: "Qatar", alpha2: "QA", alpha3: "QAT", dialCode: "+974", currency: "QAR" },
  { name: "Kuwait", alpha2: "KW", alpha3: "KWT", dialCode: "+965", currency: "KWD" },
  { name: "Bahrain", alpha2: "BH", alpha3: "BHR", dialCode: "+973", currency: "BHD" },
  { name: "Oman", alpha2: "OM", alpha3: "OMN", dialCode: "+968", currency: "OMR" },
  { name: "Jordan", alpha2: "JO", alpha3: "JOR", dialCode: "+962", currency: "JOD" },
  { name: "Lebanon", alpha2: "LB", alpha3: "LBN", dialCode: "+961", currency: "LBP" },
  { name: "Egypt", alpha2: "EG", alpha3: "EGY", dialCode: "+20", currency: "EGP" },
  { name: "Morocco", alpha2: "MA", alpha3: "MAR", dialCode: "+212", currency: "MAD" },
  { name: "Tunisia", alpha2: "TN", alpha3: "TUN", dialCode: "+216", currency: "TND" },
  { name: "Algeria", alpha2: "DZ", alpha3: "DZA", dialCode: "+213", currency: "DZD" },
  { name: "Libya", alpha2: "LY", alpha3: "LBY", dialCode: "+218", currency: "LYD" },
  { name: "Turkey", alpha2: "TR", alpha3: "TUR", dialCode: "+90", currency: "TRY" },
  { name: "Nigeria", alpha2: "NG", alpha3: "NGA", dialCode: "+234", currency: "NGN" },
  { name: "Ghana", alpha2: "GH", alpha3: "GHA", dialCode: "+233", currency: "GHS" },
  { name: "Kenya", alpha2: "KE", alpha3: "KEN", dialCode: "+254", currency: "KES" },
  { name: "South Africa", alpha2: "ZA", alpha3: "ZAF", dialCode: "+27", currency: "ZAR" },
  { name: "Ethiopia", alpha2: "ET", alpha3: "ETH", dialCode: "+251", currency: "ETB" },
  { name: "Tanzania", alpha2: "TZ", alpha3: "TZA", dialCode: "+255", currency: "TZS" },
  { name: "Uganda", alpha2: "UG", alpha3: "UGA", dialCode: "+256", currency: "UGX" },
  { name: "Rwanda", alpha2: "RW", alpha3: "RWA", dialCode: "+250", currency: "RWF" },
  { name: "Senegal", alpha2: "SN", alpha3: "SEN", dialCode: "+221", currency: "XOF" },
  { name: "Ivory Coast", alpha2: "CI", alpha3: "CIV", dialCode: "+225", currency: "XOF" },
  { name: "Cameroon", alpha2: "CM", alpha3: "CMR", dialCode: "+237", currency: "XAF" },
  { name: "Mauritius", alpha2: "MU", alpha3: "MUS", dialCode: "+230", currency: "MUR" },
  { name: "Seychelles", alpha2: "SC", alpha3: "SYC", dialCode: "+248", currency: "SCR" },
  { name: "Cape Verde", alpha2: "CV", alpha3: "CPV", dialCode: "+238", currency: "CVE" },
  { name: "Zimbabwe", alpha2: "ZW", alpha3: "ZWE", dialCode: "+263", currency: "USD" },
  { name: "Botswana", alpha2: "BW", alpha3: "BWA", dialCode: "+267", currency: "BWP" },
  { name: "Namibia", alpha2: "NA", alpha3: "NAM", dialCode: "+264", currency: "NAD" },
  { name: "Mozambique", alpha2: "MZ", alpha3: "MOZ", dialCode: "+258", currency: "MZN" },
  { name: "Angola", alpha2: "AO", alpha3: "AGO", dialCode: "+244", currency: "AOA" },
  { name: "DR Congo", alpha2: "CD", alpha3: "COD", dialCode: "+243", currency: "CDF" },
  { name: "Sudan", alpha2: "SD", alpha3: "SDN", dialCode: "+249", currency: "SDG" },
  { name: "Somalia", alpha2: "SO", alpha3: "SOM", dialCode: "+252", currency: "SOS" },
  { name: "Djibouti", alpha2: "DJ", alpha3: "DJI", dialCode: "+253", currency: "DJF" },
  { name: "Eritrea", alpha2: "ER", alpha3: "ERI", dialCode: "+291", currency: "ERN" },
  { name: "Chad", alpha2: "TD", alpha3: "TCD", dialCode: "+235", currency: "XAF" },
  { name: "Niger", alpha2: "NE", alpha3: "NER", dialCode: "+227", currency: "XOF" },
  { name: "Mali", alpha2: "ML", alpha3: "MLI", dialCode: "+223", currency: "XOF" },
  { name: "Burkina Faso", alpha2: "BF", alpha3: "BFA", dialCode: "+226", currency: "XOF" },
  { name: "Guinea", alpha2: "GN", alpha3: "GIN", dialCode: "+224", currency: "GNF" },
  { name: "Liberia", alpha2: "LR", alpha3: "LBR", dialCode: "+231", currency: "LRD" },
  { name: "Sierra Leone", alpha2: "SL", alpha3: "SLE", dialCode: "+232", currency: "SLL" },
  { name: "Gambia", alpha2: "GM", alpha3: "GMB", dialCode: "+220", currency: "GMD" },
  { name: "Mauritania", alpha2: "MR", alpha3: "MRT", dialCode: "+222", currency: "MRU" },
  { name: "Gabon", alpha2: "GA", alpha3: "GAB", dialCode: "+241", currency: "XAF" },
  { name: "Congo", alpha2: "CG", alpha3: "COG", dialCode: "+242", currency: "XAF" },
  { name: "Equatorial Guinea", alpha2: "GQ", alpha3: "GNQ", dialCode: "+240", currency: "XAF" },
  { name: "Central African Republic", alpha2: "CF", alpha3: "CAF", dialCode: "+236", currency: "XAF" },
  { name: "Benin", alpha2: "BJ", alpha3: "BEN", dialCode: "+229", currency: "XOF" },
  { name: "Togo", alpha2: "TG", alpha3: "TGO", dialCode: "+228", currency: "XOF" },
  { name: "Madagascar", alpha2: "MG", alpha3: "MDG", dialCode: "+261", currency: "MGA" },
  { name: "Malawi", alpha2: "MW", alpha3: "MWI", dialCode: "+265", currency: "MWK" },
  { name: "Zambia", alpha2: "ZM", alpha3: "ZMB", dialCode: "+260", currency: "ZMW" },
  { name: "Eswatini", alpha2: "SZ", alpha3: "SWZ", dialCode: "+268", currency: "SZL" },
  { name: "Lesotho", alpha2: "LS", alpha3: "LSO", dialCode: "+266", currency: "LSL" },
  { name: "Burundi", alpha2: "BI", alpha3: "BDI", dialCode: "+257", currency: "BIF" },
  { name: "Comoros", alpha2: "KM", alpha3: "COM", dialCode: "+269", currency: "KMF" },
  { name: "France", alpha2: "FR", alpha3: "FRA", dialCode: "+33", currency: "EUR" },
  { name: "Germany", alpha2: "DE", alpha3: "DEU", dialCode: "+49", currency: "EUR" },
  { name: "Spain", alpha2: "ES", alpha3: "ESP", dialCode: "+34", currency: "EUR" },
  { name: "Italy", alpha2: "IT", alpha3: "ITA", dialCode: "+39", currency: "EUR" },
  { name: "Portugal", alpha2: "PT", alpha3: "PRT", dialCode: "+351", currency: "EUR" },
  { name: "Netherlands", alpha2: "NL", alpha3: "NLD", dialCode: "+31", currency: "EUR" },
  { name: "Belgium", alpha2: "BE", alpha3: "BEL", dialCode: "+32", currency: "EUR" },
  { name: "Luxembourg", alpha2: "LU", alpha3: "LUX", dialCode: "+352", currency: "EUR" },
  { name: "Ireland", alpha2: "IE", alpha3: "IRL", dialCode: "+353", currency: "EUR" },
  { name: "Austria", alpha2: "AT", alpha3: "AUT", dialCode: "+43", currency: "EUR" },
  { name: "Switzerland", alpha2: "CH", alpha3: "CHE", dialCode: "+41", currency: "CHF" },
  { name: "Sweden", alpha2: "SE", alpha3: "SWE", dialCode: "+46", currency: "SEK" },
  { name: "Norway", alpha2: "NO", alpha3: "NOR", dialCode: "+47", currency: "NOK" },
  { name: "Denmark", alpha2: "DK", alpha3: "DNK", dialCode: "+45", currency: "DKK" },
  { name: "Finland", alpha2: "FI", alpha3: "FIN", dialCode: "+358", currency: "EUR" },
  { name: "Iceland", alpha2: "IS", alpha3: "ISL", dialCode: "+354", currency: "ISK" },
  { name: "Poland", alpha2: "PL", alpha3: "POL", dialCode: "+48", currency: "PLN" },
  { name: "Czech Republic", alpha2: "CZ", alpha3: "CZE", dialCode: "+420", currency: "CZK" },
  { name: "Slovakia", alpha2: "SK", alpha3: "SVK", dialCode: "+421", currency: "EUR" },
  { name: "Hungary", alpha2: "HU", alpha3: "HUN", dialCode: "+36", currency: "HUF" },
  { name: "Romania", alpha2: "RO", alpha3: "ROU", dialCode: "+40", currency: "RON" },
  { name: "Bulgaria", alpha2: "BG", alpha3: "BGR", dialCode: "+359", currency: "BGN" },
  { name: "Greece", alpha2: "GR", alpha3: "GRC", dialCode: "+30", currency: "EUR" },
  { name: "Cyprus", alpha2: "CY", alpha3: "CYP", dialCode: "+357", currency: "EUR" },
  { name: "Malta", alpha2: "MT", alpha3: "MLT", dialCode: "+356", currency: "EUR" },
  { name: "Croatia", alpha2: "HR", alpha3: "HRV", dialCode: "+385", currency: "EUR" },
  { name: "Slovenia", alpha2: "SI", alpha3: "SVN", dialCode: "+386", currency: "EUR" },
  { name: "Estonia", alpha2: "EE", alpha3: "EST", dialCode: "+372", currency: "EUR" },
  { name: "Latvia", alpha2: "LV", alpha3: "LVA", dialCode: "+371", currency: "EUR" },
  { name: "Lithuania", alpha2: "LT", alpha3: "LTU", dialCode: "+370", currency: "EUR" },
  { name: "Serbia", alpha2: "RS", alpha3: "SRB", dialCode: "+381", currency: "RSD" },
  { name: "Ukraine", alpha2: "UA", alpha3: "UKR", dialCode: "+380", currency: "UAH" },
  { name: "Moldova", alpha2: "MD", alpha3: "MDA", dialCode: "+373", currency: "MDL" },
  { name: "Belarus", alpha2: "BY", alpha3: "BLR", dialCode: "+375", currency: "BYN" },
  { name: "Georgia", alpha2: "GE", alpha3: "GEO", dialCode: "+995", currency: "GEL" },
  { name: "Armenia", alpha2: "AM", alpha3: "ARM", dialCode: "+374", currency: "AMD" },
  { name: "Azerbaijan", alpha2: "AZ", alpha3: "AZE", dialCode: "+994", currency: "AZN" },
  { name: "Kazakhstan", alpha2: "KZ", alpha3: "KAZ", dialCode: "+7", currency: "KZT" },
  { name: "Uzbekistan", alpha2: "UZ", alpha3: "UZB", dialCode: "+998", currency: "UZS" },
  { name: "Mongolia", alpha2: "MN", alpha3: "MNG", dialCode: "+976", currency: "MNT" },
  { name: "China", alpha2: "CN", alpha3: "CHN", dialCode: "+86", currency: "CNY" },
  { name: "Japan", alpha2: "JP", alpha3: "JPN", dialCode: "+81", currency: "JPY" },
  { name: "South Korea", alpha2: "KR", alpha3: "KOR", dialCode: "+82", currency: "KRW" },
  { name: "India", alpha2: "IN", alpha3: "IND", dialCode: "+91", currency: "INR" },
  { name: "Pakistan", alpha2: "PK", alpha3: "PAK", dialCode: "+92", currency: "PKR" },
  { name: "Bangladesh", alpha2: "BD", alpha3: "BGD", dialCode: "+880", currency: "BDT" },
  { name: "Sri Lanka", alpha2: "LK", alpha3: "LKA", dialCode: "+94", currency: "LKR" },
  { name: "Nepal", alpha2: "NP", alpha3: "NPL", dialCode: "+977", currency: "NPR" },
  { name: "Bhutan", alpha2: "BT", alpha3: "BTN", dialCode: "+975", currency: "BTN" },
  { name: "Maldives", alpha2: "MV", alpha3: "MDV", dialCode: "+960", currency: "MVR" },
  { name: "Afghanistan", alpha2: "AF", alpha3: "AFG", dialCode: "+93", currency: "AFN" },
  { name: "Iran", alpha2: "IR", alpha3: "IRN", dialCode: "+98", currency: "IRR" },
  { name: "Iraq", alpha2: "IQ", alpha3: "IRQ", dialCode: "+964", currency: "IQD" },
  { name: "Syria", alpha2: "SY", alpha3: "SYR", dialCode: "+963", currency: "SYP" },
  { name: "Israel", alpha2: "IL", alpha3: "ISR", dialCode: "+972", currency: "ILS" },
  { name: "Palestine", alpha2: "PS", alpha3: "PSE", dialCode: "+970", currency: "ILS" },
  { name: "Singapore", alpha2: "SG", alpha3: "SGP", dialCode: "+65", currency: "SGD" },
  { name: "Malaysia", alpha2: "MY", alpha3: "MYS", dialCode: "+60", currency: "MYR" },
  { name: "Indonesia", alpha2: "ID", alpha3: "IDN", dialCode: "+62", currency: "IDR" },
  { name: "Philippines", alpha2: "PH", alpha3: "PHL", dialCode: "+63", currency: "PHP" },
  { name: "Thailand", alpha2: "TH", alpha3: "THA", dialCode: "+66", currency: "THB" },
  { name: "Vietnam", alpha2: "VN", alpha3: "VNM", dialCode: "+84", currency: "VND" },
  { name: "Cambodia", alpha2: "KH", alpha3: "KHM", dialCode: "+855", currency: "KHR" },
  { name: "Laos", alpha2: "LA", alpha3: "LAO", dialCode: "+856", currency: "LAK" },
  { name: "Myanmar", alpha2: "MM", alpha3: "MMR", dialCode: "+95", currency: "MMK" },
  { name: "Brunei", alpha2: "BN", alpha3: "BRN", dialCode: "+673", currency: "BND" },
  { name: "Hong Kong", alpha2: "HK", alpha3: "HKG", dialCode: "+852", currency: "HKD" },
  { name: "Taiwan", alpha2: "TW", alpha3: "TWN", dialCode: "+886", currency: "TWD" },
  { name: "Macau", alpha2: "MO", alpha3: "MAC", dialCode: "+853", currency: "MOP" },
  { name: "Australia", alpha2: "AU", alpha3: "AUS", dialCode: "+61", currency: "AUD" },
  { name: "New Zealand", alpha2: "NZ", alpha3: "NZL", dialCode: "+64", currency: "NZD" },
  { name: "Fiji", alpha2: "FJ", alpha3: "FJI", dialCode: "+679", currency: "FJD" },
  { name: "Papua New Guinea", alpha2: "PG", alpha3: "PNG", dialCode: "+675", currency: "PGK" },
  { name: "Canada", alpha2: "CA", alpha3: "CAN", dialCode: "+1", currency: "CAD" },
  { name: "Mexico", alpha2: "MX", alpha3: "MEX", dialCode: "+52", currency: "MXN" },
  { name: "Brazil", alpha2: "BR", alpha3: "BRA", dialCode: "+55", currency: "BRL" },
  { name: "Argentina", alpha2: "AR", alpha3: "ARG", dialCode: "+54", currency: "ARS" },
  { name: "Chile", alpha2: "CL", alpha3: "CHL", dialCode: "+56", currency: "CLP" },
  { name: "Colombia", alpha2: "CO", alpha3: "COL", dialCode: "+57", currency: "COP" },
  { name: "Peru", alpha2: "PE", alpha3: "PER", dialCode: "+51", currency: "PEN" },
  { name: "Venezuela", alpha2: "VE", alpha3: "VEN", dialCode: "+58", currency: "VES" },
  { name: "Ecuador", alpha2: "EC", alpha3: "ECU", dialCode: "+593", currency: "USD" },
  { name: "Uruguay", alpha2: "UY", alpha3: "URY", dialCode: "+598", currency: "UYU" },
  { name: "Paraguay", alpha2: "PY", alpha3: "PRY", dialCode: "+595", currency: "PYG" },
  { name: "Bolivia", alpha2: "BO", alpha3: "BOL", dialCode: "+591", currency: "BOB" },
  { name: "Panama", alpha2: "PA", alpha3: "PAN", dialCode: "+507", currency: "PAB" },
  { name: "Costa Rica", alpha2: "CR", alpha3: "CRI", dialCode: "+506", currency: "CRC" },
  { name: "Guatemala", alpha2: "GT", alpha3: "GTM", dialCode: "+502", currency: "GTQ" },
  { name: "Honduras", alpha2: "HN", alpha3: "HND", dialCode: "+504", currency: "HNL" },
  { name: "Nicaragua", alpha2: "NI", alpha3: "NIC", dialCode: "+505", currency: "NIO" },
  { name: "El Salvador", alpha2: "SV", alpha3: "SLV", dialCode: "+503", currency: "USD" },
  { name: "Dominican Republic", alpha2: "DO", alpha3: "DOM", dialCode: "+1", currency: "DOP" },
  { name: "Cuba", alpha2: "CU", alpha3: "CUB", dialCode: "+53", currency: "CUP" },
  { name: "Jamaica", alpha2: "JM", alpha3: "JAM", dialCode: "+1", currency: "JMD" },
  { name: "Trinidad and Tobago", alpha2: "TT", alpha3: "TTO", dialCode: "+1", currency: "TTD" },
  { name: "Bahamas", alpha2: "BS", alpha3: "BHS", dialCode: "+1", currency: "BSD" },
  { name: "Barbados", alpha2: "BB", alpha3: "BRB", dialCode: "+1", currency: "BBD" },
  { name: "Cayman Islands", alpha2: "KY", alpha3: "CYM", dialCode: "+1", currency: "KYD" },
  { name: "Bermuda", alpha2: "BM", alpha3: "BMU", dialCode: "+1", currency: "BMD" },
  { name: "Suriname", alpha2: "SR", alpha3: "SUR", dialCode: "+597", currency: "SRD" },
  { name: "Guyana", alpha2: "GY", alpha3: "GUY", dialCode: "+592", currency: "GYD" },
  { name: "Belize", alpha2: "BZ", alpha3: "BLZ", dialCode: "+501", currency: "BZD" },
  { name: "Netherlands Antilles (Curaçao)", alpha2: "CW", alpha3: "CUW", dialCode: "+599", currency: "ANG" },
  { name: "Aruba", alpha2: "AW", alpha3: "ABW", dialCode: "+297", currency: "AWG" },
  { name: "Russia", alpha2: "RU", alpha3: "RUS", dialCode: "+7", currency: "RUB" },
  { name: "Kyrgyzstan", alpha2: "KG", alpha3: "KGZ", dialCode: "+996", currency: "KGS" },
  { name: "Tajikistan", alpha2: "TJ", alpha3: "TJK", dialCode: "+992", currency: "TJS" },
  { name: "Turkmenistan", alpha2: "TM", alpha3: "TKM", dialCode: "+993", currency: "TMT" },
  { name: "Albania", alpha2: "AL", alpha3: "ALB", dialCode: "+355", currency: "ALL" },
  { name: "North Macedonia", alpha2: "MK", alpha3: "MKD", dialCode: "+389", currency: "MKD" },
  { name: "Bosnia and Herzegovina", alpha2: "BA", alpha3: "BIH", dialCode: "+387", currency: "BAM" },
  { name: "Montenegro", alpha2: "ME", alpha3: "MNE", dialCode: "+382", currency: "EUR" },
  { name: "Kosovo", alpha2: "XK", alpha3: "XKX", dialCode: "+383", currency: "EUR" },
];

export const COUNTRIES_BY_CODE: Record<string, CountryInfo> = Object.fromEntries(
  COUNTRIES.map((c) => [c.alpha2, c])
);

export function getCountry(alpha2: string): CountryInfo | undefined {
  return COUNTRIES_BY_CODE[alpha2.toUpperCase()];
}
