/**
 * ISO 4217 currency metadata + crypto assets (sandbox).
 * decimals = exponent used for minor units / rounding.
 */

export interface CurrencyInfo {
  code: string;
  name: string;
  symbol: string;
  decimals: number;
  /** true when it is a crypto asset */
  crypto?: boolean;
  /** ISO 4217 numeric code when available */
  numeric?: string;
}

export const CURRENCIES: Record<string, CurrencyInfo> = {
  // Major fiat (ISO 4217)
  USD: { code: "USD", name: "US Dollar", symbol: "$", decimals: 2, numeric: "840" },
  EUR: { code: "EUR", name: "Euro", symbol: "€", decimals: 2, numeric: "978" },
  GBP: { code: "GBP", name: "British Pound", symbol: "£", decimals: 2, numeric: "826" },
  JPY: { code: "JPY", name: "Japanese Yen", symbol: "¥", decimals: 0, numeric: "392" },
  CHF: { code: "CHF", name: "Swiss Franc", symbol: "CHF", decimals: 2, numeric: "756" },
  CAD: { code: "CAD", name: "Canadian Dollar", symbol: "C$", decimals: 2, numeric: "124" },
  AUD: { code: "AUD", name: "Australian Dollar", symbol: "A$", decimals: 2, numeric: "036" },
  NZD: { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", decimals: 2, numeric: "554" },
  SGD: { code: "SGD", name: "Singapore Dollar", symbol: "S$", decimals: 2, numeric: "702" },
  HKD: { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", decimals: 2, numeric: "344" },
  CNY: { code: "CNY", name: "Chinese Yuan", symbol: "¥", decimals: 2, numeric: "156" },
  KRW: { code: "KRW", name: "South Korean Won", symbol: "₩", decimals: 0, numeric: "410" },
  INR: { code: "INR", name: "Indian Rupee", symbol: "₹", decimals: 2, numeric: "356" },
  BRL: { code: "BRL", name: "Brazilian Real", symbol: "R$", decimals: 2, numeric: "986" },
  MXN: { code: "MXN", name: "Mexican Peso", symbol: "MX$", decimals: 2, numeric: "484" },
  ZAR: { code: "ZAR", name: "South African Rand", symbol: "R", decimals: 2, numeric: "710" },
  AED: { code: "AED", name: "UAE Dirham", symbol: "د.إ", decimals: 2, numeric: "784" },
  SAR: { code: "SAR", name: "Saudi Riyal", symbol: "﷼", decimals: 2, numeric: "682" },
  QAR: { code: "QAR", name: "Qatari Riyal", symbol: "﷼", decimals: 2, numeric: "634" },
  KWD: { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimals: 3, numeric: "414" },
  BHD: { code: "BHD", name: "Bahraini Dinar", symbol: "ب.د", decimals: 3, numeric: "048" },
  OMR: { code: "OMR", name: "Omani Rial", symbol: "﷼", decimals: 3, numeric: "512" },
  JOD: { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", decimals: 3, numeric: "400" },
  TRY: { code: "TRY", name: "Turkish Lira", symbol: "₺", decimals: 2, numeric: "949" },
  RUB: { code: "RUB", name: "Russian Ruble", symbol: "₽", decimals: 2, numeric: "643" },
  PLN: { code: "PLN", name: "Polish Zloty", symbol: "zł", decimals: 2, numeric: "985" },
  CZK: { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimals: 2, numeric: "203" },
  HUF: { code: "HUF", name: "Hungarian Forint", symbol: "Ft", decimals: 2, numeric: "348" },
  SEK: { code: "SEK", name: "Swedish Krona", symbol: "kr", decimals: 2, numeric: "752" },
  NOK: { code: "NOK", name: "Norwegian Krone", symbol: "kr", decimals: 2, numeric: "578" },
  DKK: { code: "DKK", name: "Danish Krone", symbol: "kr", decimals: 2, numeric: "208" },
  ISK: { code: "ISK", name: "Icelandic Krona", symbol: "kr", decimals: 0, numeric: "352" },
  ILS: { code: "ILS", name: "Israeli Shekel", symbol: "₪", decimals: 2, numeric: "376" },
  THB: { code: "THB", name: "Thai Baht", symbol: "฿", decimals: 2, numeric: "764" },
  MYR: { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimals: 2, numeric: "458" },
  IDR: { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimals: 2, numeric: "360" },
  PHP: { code: "PHP", name: "Philippine Peso", symbol: "₱", decimals: 2, numeric: "608" },
  VND: { code: "VND", name: "Vietnamese Dong", symbol: "₫", decimals: 0, numeric: "704" },
  PKR: { code: "PKR", name: "Pakistani Rupee", symbol: "₨", decimals: 2, numeric: "586" },
  BDT: { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimals: 2, numeric: "050" },
  LKR: { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", decimals: 2, numeric: "144" },
  NGN: { code: "NGN", name: "Nigerian Naira", symbol: "₦", decimals: 2, numeric: "566" },
  KES: { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimals: 2, numeric: "404" },
  EGP: { code: "EGP", name: "Egyptian Pound", symbol: "E£", decimals: 2, numeric: "818" },
  MAD: { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", decimals: 2, numeric: "504" },
  TND: { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimals: 3, numeric: "788" },
  DZD: { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", decimals: 2, numeric: "012" },
  GHS: { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵", decimals: 2, numeric: "936" },
  ETB: { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimals: 2, numeric: "230" },
  ARS: { code: "ARS", name: "Argentine Peso", symbol: "$", decimals: 2, numeric: "032" },
  CLP: { code: "CLP", name: "Chilean Peso", symbol: "$", decimals: 0, numeric: "152" },
  COP: { code: "COP", name: "Colombian Peso", symbol: "$", decimals: 2, numeric: "170" },
  PEN: { code: "PEN", name: "Peruvian Sol", symbol: "S/", decimals: 2, numeric: "604" },
  UAH: { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimals: 2, numeric: "980" },
  RON: { code: "RON", name: "Romanian Leu", symbol: "lei", decimals: 2, numeric: "946" },
  BGN: { code: "BGN", name: "Bulgarian Lev", symbol: "лв", decimals: 2, numeric: "975" },
  RSD: { code: "RSD", name: "Serbian Dinar", symbol: "дин", decimals: 2, numeric: "941" },
  KZT: { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimals: 2, numeric: "398" },
  UZS: { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", decimals: 2, numeric: "860" },
  AZN: { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", decimals: 2, numeric: "944" },
  GEL: { code: "GEL", name: "Georgian Lari", symbol: "₾", decimals: 2, numeric: "981" },
  AMD: { code: "AMD", name: "Armenian Dram", symbol: "֏", decimals: 2, numeric: "051" },
  MDL: { code: "MDL", name: "Moldovan Leu", symbol: "L", decimals: 2, numeric: "498" },
  BYN: { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimals: 2, numeric: "933" },
  MNT: { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", decimals: 2, numeric: "496" },
  FJD: { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", decimals: 2, numeric: "242" },
  PGK: { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimals: 2, numeric: "598" },
  TTD: { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$", decimals: 2, numeric: "780" },
  JMD: { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimals: 2, numeric: "388" },
  XCD: { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", decimals: 2, numeric: "951" },
  BBD: { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", decimals: 2, numeric: "052" },
  BZD: { code: "BZD", name: "Belize Dollar", symbol: "BZ$", decimals: 2, numeric: "084" },
  BOB: { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", decimals: 2, numeric: "068" },
  PYG: { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", decimals: 0, numeric: "600" },
  UYU: { code: "UYU", name: "Uruguayan Peso", symbol: "$U", decimals: 2, numeric: "858" },
  CRC: { code: "CRC", name: "Costa Rican Colon", symbol: "₡", decimals: 2, numeric: "188" },
  DOP: { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimals: 2, numeric: "214" },
  HTG: { code: "HTG", name: "Haitian Gourde", symbol: "G", decimals: 2, numeric: "332" },
  NIO: { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$", decimals: 2, numeric: "558" },
  HNL: { code: "HNL", name: "Honduran Lempira", symbol: "L", decimals: 2, numeric: "340" },
  GTQ: { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimals: 2, numeric: "320" },
  PAB: { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimals: 2, numeric: "590" },
  CUP: { code: "CUP", name: "Cuban Peso", symbol: "$", decimals: 2, numeric: "192" },
  ANG: { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimals: 2, numeric: "532" },
  AWG: { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimals: 2, numeric: "533" },
  BSD: { code: "BSD", name: "Bahamian Dollar", symbol: "B$", decimals: 2, numeric: "044" },
  KYD: { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", decimals: 2, numeric: "136" },
  GYD: { code: "GYD", name: "Guyanese Dollar", symbol: "G$", decimals: 2, numeric: "328" },
  SRD: { code: "SRD", name: "Surinamese Dollar", symbol: "SRD", decimals: 2, numeric: "968" },
  CVE: { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", decimals: 2, numeric: "132" },
  SLL: { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", decimals: 2, numeric: "694" },
  LRD: { code: "LRD", name: "Liberian Dollar", symbol: "L$", decimals: 2, numeric: "430" },
  GMD: { code: "GMD", name: "Gambian Dalasi", symbol: "D", decimals: 2, numeric: "270" },
  MRU: { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", decimals: 2, numeric: "929" },
  SHP: { code: "SHP", name: "Saint Helena Pound", symbol: "£", decimals: 2, numeric: "654" },
  STN: { code: "STN", name: "Sao Tome Dobra", symbol: "Db", decimals: 2, numeric: "930" },
  TOP: { code: "TOP", name: "Tongan Pa'anga", symbol: "T$", decimals: 2, numeric: "776" },
  WST: { code: "WST", name: "Samoan Tala", symbol: "WS$", decimals: 2, numeric: "882" },
  VUV: { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", decimals: 0, numeric: "548" },
  SBD: { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", decimals: 2, numeric: "090" },
  AUD_X: { code: "AUD", name: "Australian Dollar", symbol: "A$", decimals: 2 },
  XPF: { code: "XPF", name: "CFP Franc", symbol: "₣", decimals: 0, numeric: "953" },
  XOF: { code: "XOF", name: "West African CFA Franc", symbol: "CFA", decimals: 0, numeric: "952" },
  XAF: { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", decimals: 0, numeric: "950" },
  MUR: { code: "MUR", name: "Mauritian Rupee", symbol: "₨", decimals: 2, numeric: "480" },
  SCR: { code: "SCR", name: "Seychellois Rupee", symbol: "₨", decimals: 2, numeric: "690" },
  MVR: { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", decimals: 2, numeric: "462" },
  NPR: { code: "NPR", name: "Nepalese Rupee", symbol: "₨", decimals: 2, numeric: "524" },
  BTN: { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimals: 2, numeric: "064" },
  AFN: { code: "AFN", name: "Afghan Afghani", symbol: "؋", decimals: 2, numeric: "971" },
  IRR: { code: "IRR", name: "Iranian Rial", symbol: "﷼", decimals: 2, numeric: "364" },
  IQD: { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimals: 3, numeric: "368" },
  SYP: { code: "SYP", name: "Syrian Pound", symbol: "£S", decimals: 2, numeric: "760" },
  LBP: { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", decimals: 2, numeric: "422" },
  YER: { code: "YER", name: "Yemeni Rial", symbol: "﷼", decimals: 2, numeric: "886" },
  MMK: { code: "MMK", name: "Myanmar Kyat", symbol: "K", decimals: 2, numeric: "104" },
  KHR: { code: "KHR", name: "Cambodian Riel", symbol: "៛", decimals: 2, numeric: "116" },
  LAK: { code: "LAK", name: "Lao Kip", symbol: "₭", decimals: 2, numeric: "418" },
  BND: { code: "BND", name: "Brunei Dollar", symbol: "B$", decimals: 2, numeric: "096" },
  TWD: { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimals: 2, numeric: "901" },
  MOP: { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", decimals: 2, numeric: "446" },
  KGS: { code: "KGS", name: "Kyrgyzstani Som", symbol: "сом", decimals: 2, numeric: "417" },
  TJS: { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", decimals: 2, numeric: "972" },
  TMT: { code: "TMT", name: "Turkmenistani Manat", symbol: "m", decimals: 2, numeric: "934" },

  // Crypto (sandbox custodial assets)
  BTC: { code: "BTC", name: "Bitcoin", symbol: "₿", decimals: 8, crypto: true },
  ETH: { code: "ETH", name: "Ethereum", symbol: "Ξ", decimals: 8, crypto: true },
  SOL: { code: "SOL", name: "Solana", symbol: "SOL", decimals: 8, crypto: true },
  USDT: { code: "USDT", name: "Tether USD", symbol: "₮", decimals: 2, crypto: true },
  USDC: { code: "USDC", name: "USD Coin", symbol: "USDC", decimals: 2, crypto: true },
  XRP: { code: "XRP", name: "XRP", symbol: "XRP", decimals: 8, crypto: true },
  BNB: { code: "BNB", name: "BNB", symbol: "BNB", decimals: 8, crypto: true },
  ADA: { code: "ADA", name: "Cardano", symbol: "ADA", decimals: 8, crypto: true },
  DOT: { code: "DOT", name: "Polkadot", symbol: "DOT", decimals: 8, crypto: true },
  LTC: { code: "LTC", name: "Litecoin", symbol: "Ł", decimals: 8, crypto: true },
  DOGE: { code: "DOGE", name: "Dogecoin", symbol: "Ð", decimals: 8, crypto: true },
  AVAX: { code: "AVAX", name: "Avalanche", symbol: "AVAX", decimals: 8, crypto: true },
  LINK: { code: "LINK", name: "Chainlink", symbol: "LINK", decimals: 8, crypto: true },
  UNI: { code: "UNI", name: "Uniswap", symbol: "UNI", decimals: 8, crypto: true },
  ATOM: { code: "ATOM", name: "Cosmos", symbol: "ATOM", decimals: 8, crypto: true },
  TRX: { code: "TRX", name: "TRON", symbol: "TRX", decimals: 8, crypto: true },
  MATIC: { code: "MATIC", name: "Polygon", symbol: "MATIC", decimals: 8, crypto: true },
  NEAR: { code: "NEAR", name: "NEAR Protocol", symbol: "NEAR", decimals: 8, crypto: true },
  APT: { code: "APT", name: "Aptos", symbol: "APT", decimals: 8, crypto: true },
  ARB: { code: "ARB", name: "Arbitrum", symbol: "ARB", decimals: 8, crypto: true },
  OP: { code: "OP", name: "Optimism", symbol: "OP", decimals: 8, crypto: true },
  SUI: { code: "SUI", name: "Sui", symbol: "SUI", decimals: 8, crypto: true },
  SEI: { code: "SEI", name: "Sei", symbol: "SEI", decimals: 8, crypto: true },
  INJ: { code: "INJ", name: "Injective", symbol: "INJ", decimals: 8, crypto: true },
  TON: { code: "TON", name: "Toncoin", symbol: "TON", decimals: 8, crypto: true },
  XTZ: { code: "XTZ", name: "Tezos", symbol: "XTZ", decimals: 8, crypto: true },
  EGLD: { code: "EGLD", name: "MultiversX", symbol: "EGLD", decimals: 8, crypto: true },
  FIL: { code: "FIL", name: "Filecoin", symbol: "FIL", decimals: 8, crypto: true },
  ALGO: { code: "ALGO", name: "Algorand", symbol: "ALGO", decimals: 8, crypto: true },
  XLM: { code: "XLM", name: "Stellar", symbol: "XLM", decimals: 8, crypto: true },
  SHIB: { code: "SHIB", name: "Shiba Inu", symbol: "SHIB", decimals: 8, crypto: true },
  PEPE: { code: "PEPE", name: "Pepe", symbol: "PEPE", decimals: 8, crypto: true },
  BCH: { code: "BCH", name: "Bitcoin Cash", symbol: "BCH", decimals: 8, crypto: true },
  ETC: { code: "ETC", name: "Ethereum Classic", symbol: "ETC", decimals: 8, crypto: true },
  MKR: { code: "MKR", name: "Maker", symbol: "MKR", decimals: 8, crypto: true },
  AAVE: { code: "AAVE", name: "Aave", symbol: "AAVE", decimals: 8, crypto: true },
  GRT: { code: "GRT", name: "The Graph", symbol: "GRT", decimals: 8, crypto: true },
  RUNE: { code: "RUNE", name: "THORChain", symbol: "RUNE", decimals: 8, crypto: true },
  FET: { code: "FET", name: "Fetch.ai", symbol: "FET", decimals: 8, crypto: true },
  RNDR: { code: "RNDR", name: "Render", symbol: "RNDR", decimals: 8, crypto: true },
};

export const FIAT_CURRENCIES: CurrencyInfo[] = Object.values(CURRENCIES).filter((c) => !c.crypto);
export const CRYPTO_CURRENCIES: CurrencyInfo[] = Object.values(CURRENCIES).filter((c) => c.crypto);

export function getCurrency(code: string): CurrencyInfo {
  return CURRENCIES[code.toUpperCase()] ?? { code: code.toUpperCase(), name: code.toUpperCase(), symbol: code.toUpperCase(), decimals: 2 };
}

export function isCrypto(code: string): boolean {
  return !!CURRENCIES[code.toUpperCase()]?.crypto;
}
